### ISSUE TITLE
Random evictions in private chat room due to invitations

### ISSUE THREAD

**Issue by awishformore** [gitterHQ/gitter#1102]
When a user is invited to a private chat room on a private repository, Gitter does not ask for private repository access and the user can successfully join the chat room. Some of the messages he will write will go through (which they shouldn't). However, he will be evicted from the chat room randomly or when trying to write messages at times.

When using the URL to try accessing the private chat room, Gitter asks for private repository access, as expected and the issue doesn't arrise. I suggest that you should add this same screen for users that have been invited to a private chat room without having given private repository access to Gitter.

**Comment by MadLittleMods** [comment]
Please note that having the user being able to write messages without granting private repo scope to Gitter is completely fine, *Because* you did the permission check in order to invite them in the first place.

@mydigitalself nailed the down the idea of why this is happening in [your discussion in the `gitterHQ/gitter` room](https://gitter.im/gitterHQ/gitter?at=56b875fe9c53e6696d48bd1f).

When you add the other person to the room, we use your token to check membership. Then we do some caching on the permissions check so the user is able to join the room and act as normal but when the cache expires and do a permission check from the other persons perspective, we can't see that they have access to the repo because they haven't granted private repo access.

We should add some way to notify the user that they need to grant private repo access when they first visit the room after being invited.

---

The solution for now is to have the other user grant private repo scope which can be done by visiting the room URL manually after being kicked out and clicking the grant scope link on the 404 page or using this: https://gitter.im/login/upgrade?scopes=repo
