### ISSUE TITLE
IE11 chat area weirdness (message author and burst)

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1134]
As reported by @tomspilman.

IE11 chat area weirdness (message author and burst)

### IE11
![](http://i.imgur.com/tgh7xak.png)

### Actual
![](http://i.imgur.com/P4Cc4vk.png)

**Comment by mydigitalself** [comment]
I managed to get this on normal Chrome when @MadLittleMods and I both said something at pretty much the identical time and clearly the message burst calculation has some sort of time-based race condition that's causing this because my (the first) yes has `burstStart` and the second yes has `burstContinued class` but you will notice, in reality, Eric said yes first.

What I got:
![screen shot 2016-02-23 at 10 32 09](https://cloud.githubusercontent.com/assets/1491887/13248878/e1d98a30-da18-11e5-9057-dc72eaa2ace8.png)

Reality:
![screen shot 2016-02-23 at 10 33 48](https://cloud.githubusercontent.com/assets/1491887/13248887/f5fa4a0e-da18-11e5-95f8-85384f2bdf57.png)

**Comment by MadLittleMods** [comment]
note: I didn't see any issues when this occured

**Comment by mydigitalself** [comment]
No it's purely client side on one end. Refreshing will sort it back out again.

**Comment by MadLittleMods** [comment]
Understood, just saying that it didn't mess up in the same way it did you for. I didn't hit the race condition.

**Comment by mydigitalself** [comment]
I'd certainly take a look at the burst calculation logic and see if there's a condition that will cause a chat from a different user to **not** trigger a new burst rather than continue an existing one - especially if two chat messages arrive at the same time.

**Comment by tomspilman** [comment]
Note that in IE when this happened to me... refreshing didn't fix it.  Switching rooms didn't fix it.  I had to open a new browser window to fix it.

**Comment by MadLittleMods** [comment]
I hotfixed the issue and should be in place when the CI finishes.
