### ISSUE TITLE
Right-toolbar (sidebar) collapses when clicking children on search expand

### ISSUE THREAD

**Issue by marcoslater** [gitterHQ/gitter#1240]
When the window size is small (in my case, I have it split in the middle of the screen.) the side bar on the right becomes very hard and glitchy to interact with. 

I've recorded a quick video to show the issue: https://youtu.be/vW9zsXzfKYQ

(Desktop - Mac)

**Comment by marcoslater** [comment]
(Desktop - Mac)

**Comment by MadLittleMods** [comment]
This will be fixed when the [new left-menu](http://blog.gitter.im/2016/03/15/introducing-our-new-ui/) rolls out for everyone. When I say fixed, you won't be able to expand it anymore because search has moved to the left-menu.

Expanding the right-column isn't exactly supported behavior at the moment. You can track this by following https://github.com/gitterHQ/gitter/issues/296 and https://github.com/gitterHQ/gitter/issues/253 which will probably add a expand/collapse mechanic.

**Comment by MadLittleMods** [comment]
The [new left menu has rolled out](http://blog.gitter.im/2016/05/12/a-new-look-for-gitter/) and search has been moved to the left menu.
