### ISSUE TITLE
Broken Links when using #issuenumber in non-primary channel

### ISSUE THREAD

**Issue by PFCKrutonium** [gitterHQ/gitter#1293]
For example if you type `#99999` into the chat (assuming it existed) [`OpenRCT2/OpenRCT2/non-dev`](https://gitter.im/OpenRCT2/OpenRCT2/non-dev) it will create a link like this: https://github.com//issues/99999 which is obviously a bad link.

In this scenario the channel should perhaps have the ability to select a repo to reference, or just assume your referring to the main one - https://github.com/OpenRCT2/OpenRCT2/issues/99999 .

**Comment by MadLittleMods** [comment]
Good catch.

For setting the default repo reference, refer to https://github.com/gitterHQ/gitter/issues/757

**Comment by MadLittleMods** [comment]
btw, this [now works for your room](https://gitter.im/OpenRCT2/OpenRCT2/non-dev?at=575a784f5eecfbd755f7451c) ever since we changed to communities and pull from the security descriptor of the room which points to the repo in that rooms case.

We also recently [upgraded the issue decorator](https://github.com/troupe/gitter-webapp/pull/2137) to add some logic even if a repo isn't found for the room. (fallbacks in this order)

 - If room has `sd.type === 'GH_REPO'` : `https://github.com/' + sd.linkPath + '/issues/xxx`
 - If one to one room: `https://github.com/issues?q=xxx+%28involves%3A' + currentUser.get('username') + '+OR+involves%3A' + otherUser.username + '+%29';`
 -  If room has `sd.type === 'GH_ORG'`: `https://github.com/issues?q=xxx+user%3A' + sd.linkPath;`
 - If is a GItHub user: `https://github.com/issues?q=xxx+involves:' + currentUser.get('username')`
 - `https://github.com/issues?q=999`
