### ISSUE TITLE
Archives 500 errors

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#1321]
Googlebot is reporting an increase in errors from archive pages.

Herewith an example: https://gitter.im/liam4/tlnccuwagnf/archives/2016/04/19

@lerouxb would you mind taking a look please?

**Comment by lerouxb** [comment]
I visited that URL, waited a bit and... something actually showed up in sentry!

https://app.getsentry.com/gitter/gitterim-backend/issues/134480413/

**Comment by lerouxb** [comment]
This should fix it: https://github.com/troupe/gitter-webapp/commit/8e058bdbc94af90ea4979ae4b98b756dc15a625a

Waiting for develop to build then I'll test it there because I don't have elasticsearch around.

**Comment by lerouxb** [comment]
Looks like it stopped crashing on develop:
https://beta.gitter.im/liam4/tlnccuwagnf/archives/2016/04/19

(make sure you're on develop, not a feature branch)

I'm still worried why this is the first time a message without html & text is encountered and if that sort of thing will break other things in the app, because I'm willing to bet that not every line of code deals with the fact that the message html might be undefined.
