### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by edi9999** [gitterHQ/gitter#1326]
When trying to post a chat message on gitter, we get `Promise` is not defined (inside qutebrowser), but I guess we would get this for any browser that doesn't yet support Promises.

**Comment by MadLittleMods** [comment]
Can you post a stacktrace? Because it is minified, etc. It would also be helpful to post some code snippets where the stacktrace points to but I understand qutebrowser may not have this nicety.

I don't see an instance where we use a `Promise` without `require('bluebird')` directly in the app but it could be in one of the libraries.

**Comment by edi9999** [comment]
I think it happens in this part of the code : 

```

**Comment by MadLittleMods** [comment]
It looks like `fontfaceobserver` doesn't bundle in a promise shim in the standalone version which is what their `package.json` main exports, https://github.com/bramstein/fontfaceobserver/blob/master/fontfaceobserver.standalone.js

**Comment by cutandpastey** [comment]
@edi9999 A fix for this has just rolled onto [next](http://next.gitter.im/) should be going into production later today. Please ping me if you have any more issues with this.
