### ISSUE TITLE
Input box hidden while hotspotting 

### ISSUE THREAD

**Issue by scottleibrand** [gitterHQ/gitter#1352]
With the new Gitter app's (3.5.1) new native input box, using Gitter while running a Personal Hotspot (or anything else that creates a banner at the top of the phone) hides the text input box, so that you can't see what you're typing unless you tap up top to hide the keyboard.

. | . | .
--- | --- | ---
![](http://i.imgur.com/QPEj5N0.png) | ![](http://i.imgur.com/QN7K3kD.png) | ![](http://i.imgur.com/sDqPx8X.png)

**Comment by scottleibrand** [comment]
No, it's completely hidden until you type more than one line.

**Comment by trevorah** [comment]
Thanks @scottleibrand. It looks like one of our constraints is breaking. Investigating now...

**Comment by trevorah** [comment]
@scottleibrand A workaround for now would be to rotate the phone into landscape mode. I'll try and find a proper fix though.

**Comment by trevorah** [comment]
I've got a fix!

Turns out there is a bug with ios 9 where the statusbar banner slides the keyboard down 40pts. Apple's keyboard counteracts this by rendering itself 40pts higher (third party keyboards arnt so lucky). However, when they render 40pts higher, they dont change the reported keyboard frame. Thanfully, its just a matter of detecting this and tweaking our calculations.

The fix should be out in v3.6.1
