### ISSUE TITLE
What defines a .contributor and a .admin?

### ISSUE THREAD

**Issue by liam4** [gitterHQ/gitter#1365]
I've noticed in *some* chatrooms there are bars below some of the profile pictures. Closer inspection revealed classes on the profile pictures (the `.avatar` elements) - `.admin` for black bars and `.contributor` for blue bars.

But I can't figure out how `.contributors` and `.admin`s are defined.

My assumption was GitHub repos, since none of the rooms not linked to GH repos had those bars. But then I went to one room that *was* linked, and none of the `.avatar`s were `.admin`s or `.contributors` (despite the fact that there were commits in the Activity section of the sidebar)..

**Comment by MadLittleMods** [comment]
@liam4 Contributors are only a GitHub repo room concept, ex. https://github.com/gitterHQ/gitter/graphs/contributors

An admin is the same as a contributor but for a user repo instead of org repo.

There are more actual admins of a room compared to what it shows but those classes are a bit old and only pertain to repo rooms
