### ISSUE TITLE
Cannot create community for DivvyDAO GitHub repo

### ISSUE THREAD

**Issue by jimscarver** [gitterHQ/gitter#1386]
I am an admin for https://github.com/DivvyDAO but do not get the choice to add a community for that repo.  What is the problem?

**Comment by MadLittleMods** [comment]
Just to clear up the terminology: https://github.com/DivvyDAO is an organisation. I assume you want to create a community or room based on a repo from that org because of your phrasing.

 1. Grant permissions to allow the Gitter application to see the org https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-
 1.  If it is a private repo, use the link at the bottom of the "my repos" list or under the "All Conversations" heading dropdown to add private repo scope and also grant access on the org.
