### ISSUE TITLE
Search flexibility

### ISSUE THREAD

**Issue by RWOverdijk** [gitterHQ/gitter#1398]
When I started using gitter, it had a search option that seemed to find stuff I wasn't even looking for. Now it seems to be the opposite, and it seems to not find the stuff I'm looking for.

When typing cmd+s for instance, and typing `ppv` it doesn't find @ppvg, which is a user I'd like to talk to. I'd like to use cmd+s as a quick way to jump to a private chat I had going on.

Is this configurable? Or would this perhaps make a nice feature?

**Comment by MadLittleMods** [comment]
Related https://github.com/gitterHQ/change/issues/28

You could use the slash command in the chat input `/query @username` which has a fuzzy-ish typeahead.

**Comment by RWOverdijk** [comment]
What's the fix here?

**Comment by MadLittleMods** [comment]
@RWOverdijk I mentioned it here :point_up: [August 25, 2016 10:13 AM](https://gitter.im/gitterHQ/gitter?at=57bf0b0bb69a17aa6651cbc9). The release 18.0.0 containing the fix just rolled out to prod. It was on `next` for days.

Searching `ppv` is as expected now to find `ppvg` because we search usernames now.
