### ISSUE TITLE
Crashes when initiating one to one from members list in one to one

### ISSUE THREAD

**Issue by omundy** [gitterHQ/gitter#1409]
Crashes when initiating one to one chat from members list in one to one room.

 1. Visit a one to one room
 1. `...` menu -> Members
 1. Select the other user and start chatting with them
 1. note the crash

---

See :point_up: [August 29, 2016 8:26 PM](https://gitter.im/gitterHQ/gitter?at=57c4e0c6ca24c06c63859d81)

**Comment by trevorah** [comment]
Thanks @omundy!

It looks like the crash is happening because we are pushing the same one-to-one room on the back stack, which iOS doesnt allow.

The only new information that the members list for one-to-one rooms currently gives you is the username, but that is going to appear in the room list for the next release anyway. Therefore I think we can get away with removing the members list for one-to-one rooms in the next release.
