### ISSUE TITLE
Can't recreate deleted community 

### ISSUE THREAD

**Issue by beloshkurov** [gitterHQ/gitter#1452]
At the createcommunity action, setting gitter url to  gitter.im/pixelvalue  returns validation error due to 403 Conflict response for https://gitter.im/api/private/check-group-uri?uri=pixelvalue,  thus i'm not able to create community again.

**Comment by MadLittleMods** [comment]
There isn't a way to delete a community, only rooms. The `pixelvalue` community still exists, https://gitter.im/orgs/pixelvalue/rooms

You can create some new rooms under it with the create room modal instead of the create community flow.

![](http://i.imgur.com/zoqp8Ya.png)

![](http://i.imgur.com/IL8Lm1a.png)
