### ISSUE TITLE
Can't create community with the same name as username

### ISSUE THREAD

**Issue by jv110** [gitterHQ/gitter#1498]

**Comment by MadLittleMods** [comment]
The `jv110` community already exists, https://gitter.im/jv110/home

You can create a room in that community by selecting it in the create room modal's community dropdown.

**Comment by jv110** [comment]
@MadLittleMods For me, it gives a 404 error, and I never created that community.

**Comment by MadLittleMods** [comment]
@jv110 The `jv110` community is backed by `type: GH_USER` which means it is legacy and created a while ago. But it was created by you because the `externalId` also matches your GitHub user ID, `7979845`.

Mind if I authenticate as you(no credentials needed, just asking permission) and try to see why you might be getting that 404 for the `homeUri`, https://gitter.im/jv110/home?

**Comment by jv110** [comment]
Sure, go ahead
