### ISSUE TITLE
Getting notifications after Exiting Gitter Client on Ubuntu 16.04 Desktop version

### ISSUE THREAD

**Issue by C-F-4** [gitterHQ/gitter#1562]
I'm getting notifications after Exit. My Speculation is the notifications work in a queue or something like that so I kept on getting the notifications even after "Exit Gitter" but Gitter didn't clear the queue before Exiting and the process separately kept on showing notifications til they were finished. and it's not from the Service Worker. I double checked.

**Comment by MadLittleMods** [comment]
Please create separate issues for each thing you are running into. Provide screenshots and logs.

I'll address the notifications after exit issue here.

---

It's unclear how long after exiting you are still getting notifications. If you just got a bunch of notifications, perhaps the OS is just cycling them all through to make sure you see them. If you get a few right before exit, it's reasonable to see them after because it spawns a separate process to show them.

We just recently added offline push notifications and perhaps you visited Gitter in a browser and activated the service worker.

**Comment by C-F-4** [comment]
@MadLittleMods It kept on continuing til like 10 minutes "approximately". and no the Service Worker is not activated. Just confirmed. and yeah I updated the issue.

**Comment by MadLittleMods** [comment]
@C-F-4 Just to make sure, Are you sure you are exiting Gitter completely? Gitter will continue to run in the background if you are just exiting the the main window and needs to be closed from the tray icon. Your "Exit Gitter" language indicates you may be actually exiting. What is the name of the process that is left behind after you exit from the tray icon?

**Comment by C-F-4** [comment]
Yeah it was after exiting from the System Tray. And I can't tell since I don't have that many notifications now.

**Comment by MadLittleMods** [comment]
Please ping when you get some more info.
