### ISSUE TITLE
Profile Picture not updating on Gitter

### ISSUE THREAD

**Issue by AsianNudles** [gitterHQ/gitter#1639]
As title says. I updated my profile picture on GitHub but on Gitter it won't update.

**Comment by MadLittleMods** [comment]
@AsianNudles After updating your avatar on GitHub, sign out and sign back into Gitter to see it updated.

**Comment by MadLittleMods** [comment]
@AsianNudles Are you still running into issues?

**Comment by grahamperrin** [comment]
https://gitter.im/gitterHQ/gitter?at=590f852e2b926f8a6730006f (2017-05-07) @TitouanT wrote:

> My issue isn't critical but I change my profile picture and I hover my name in gitter it show's the old one, thought that it might be a question of time but I change it 4 days ago 

Above, @MadLittleMods wrote: 

> … sign out and sign back into Gitter to see it updated.

Sorry, that's not a workaround in my case. https://gitter.im/gitterHQ/gitter?at=590fdb9ee2285d3b163a6fa1 shows the outdated avatar on my profile card and: 

> cache-free reloading is not a workaround.

After signing out, then in: 

![2017-05-08 03-46](https://cloud.githubusercontent.com/assets/192271/25788541/d0495622-33a1-11e7-954a-d6a12e8ede61.png)

**Comment by TitouanT** [comment]
As said above I have the same issue. I m using firefox on linux.

**Comment by grahamperrin** [comment]
Re: https://gitter.im/gitterHQ/gitter?at=590b6ec8e1b61e9328126027 (2017-05-04) @cbj4074 replied to @schas002: 

> Yeah, there's some caching at play there. I've seen it happen in other instances. It will eventually correct itself.

– and if I recall correctly, at least one of those two people did eventually find the proper image on my profile card. Still, the proper image is not yet apparent to me.

**Comment by grahamperrin** [comment]
@TitouanT wrote: 

> @grahamperrin ok :grinning: But for me it's a bit different no ? don't you see the good one ? because @InternetUnexplorer show me that other see the good one

For @TitouanT I do not see the good one. Earlier: 

> After signing out, then in:

– I did that just once. Still: 

![2017-05-08 04-03](https://cloud.githubusercontent.com/assets/192271/25788807/c2ecda10-33a3-11e7-811d-d23596c1c3bb.png)

**Comment by TitouanT** [comment]
As said above I have the same issue. I m using firefox on linux.

**Comment by TitouanT** [comment]
It seems that it happens only on linux. I also tried with chromium but the issue is still there.
For me [this link](https://avatars-01.gitter.im/gh/uv/3/TitouanT?s=128) show the old one (like with see on the screen shot above) and same link for a friend on mac show the good one.
When I change the s attribute on that link I can see the new one, issue is only on s=128

**Comment by TitouanT** [comment]
And the exact same thing for @grahamperrin at https://avatars-05.gitter.im/gh/uv/3/grahamperrin?s=128

**Comment by mydigitalself** [comment]
@TitouanT are you able to clear your cache perhaps on your linux box? it would also help if you could show the http full response for those URL calls so we can see if there's some long-lived cache on it somehow. Cannot reproduce here at all.

**Comment by TitouanT** [comment]
@mydigitalself do you think that it comes from a cache ? For mine why not but I don't know why the picture of graham would be in my cache since I have never talk to him before. There is no html for those urls because it's just a picture.
I'am not sure that it is what you want but I have these:

## header of the response
```http
Connection: keep-alive
Date: Mon, 08 May 2017 14:49:13 GMT
Cache-Control: max-age=2592000
Etag: "ddbc4a04e46baef25380e7e7632b2409f93b29f0"
Expires: Tue, 16 May 2017 19:06:01 GMT
Server: nginx
x-timer: S1492369561.362049,VS0,VE17
Vary: Accept-Encoding
Age: 1885392
X-Cache: Hit from cloudfront
Via: 1.1 490ad4c895f20d28b1ba662692a2e249.cloudfront.net (CloudFront)
X-Amz-Cf-Id: p3zji6aWr34-HJ_hUW_o5W17fxtsLgPXUaMMMquwNEkMazu7GtHERA==
```

The state code is 304 Not Modified. But I delete the cache so ...

**Comment by grahamperrin** [comment]
After taking the screenshots above, with Firefox 53.0 (64-bit) on KDE Plasma 4 on TrueOS Desktop, I shut down the computer and drove to work. 

At work I would have had the Gitter window open without paying attention to it. 

Now at home the issue is no longer reproducible with Firefox on TrueOS Desktop. 

```text
$ date ; uptime
Mon  8 May 2017 16:24:53 BST
 4:24p.m.  up 51 mins, 2 users, load averages: 0.94, 0.78, 0.75
$ pkg info firefox | grep -i version
Version        : 53.0_2,1
$ about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
       after restart (R) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    number of cores ……………… 4
host ……………………………………………………… momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
memory ………………………………………………… 16384 MB available, 8686 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… a009033ff
OS kernel build time ………………………………………………………… Wed 2017 Mar 29 20:13:33 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… CUSTOM
TrueOS version …………………………… TrueOS-Desktop-201703201429
uptime ………………………………………………… 51 mins
user  …………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …… KDE
    sound card driver ………… pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> on hdaa1  (1p:1v/1r:1v) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… intel_drv.so 

$ 
```

I woke an adjacent notebook running KDE Plasma 5, where Gitter was running before it slept (some time on Sunday), the issue was not observable. 

I made a remote connection to a Citrix service at work, logged in to Gitter with Firefox and Internet Explorer, the issue was not observable.
