### ISSUE TITLE
Search input clearing when `enter` is pressed

### ISSUE THREAD

**Issue by waltfy** [gitterHQ/gitter#297]
If you type something onto the search input and press enter, the input and results are cleared, taking you back to where you started off.

**Comment by MadLittleMods** [comment]
I am not sure what version of Gitter, this issue was addressing but now the first search item is selected and pressing enter will navigate to the first selected item which can be a room or a permalink search result.

With the new left menu work, the search box has moved over to the left menu and pressing enter doesn't navigate you away. We do still need to work on arrow-key keyboard shortcuts for navigating results though.
