### ISSUE TITLE
Gitter mac app won't stop launching at login

### ISSUE THREAD

**Issue by thejameskyle** [gitterHQ/gitter#355]
OS X 10.10 (14A329r) (Beta build)
Gitter 1.159 (1.159)

I've removed it from my login items (from dock and system preferences), removed any launch daemons/agents I could find, and tried to make sure OS X wasn't just trying to restore my session.

**Comment by Lbatson** [comment]
OSX 10.10.1
Gitter 1.162

i'm experiencing this as well. it's not listed in the login items, recent items set to none but still opens every time I log in, pretty annoying.

**Comment by andreacfm** [comment]
Same here! I cannot even find a way to remove it !!!! Any suggestion?

**Comment by mydigitalself** [comment]
@Lbatson @andreacfm Can you guys check something for me please.

1) Open Gitter client, click on Gitter menu in the Mac menu bar and make sure **Launch on Startup** is unchecked.
2) Quit Gitter entirely (CMD+Q style) & Reboot

Does Gitter start?

**Comment by Lbatson** [comment]
@mydigitalself that worked! I don't know how i missed that option, don't remember seeing it before. thanks.

**Comment by timfallmk** [comment]
I have the same issue as above, and all the launch options (including the Launch on Startup mentioned above) is unset. It still comes up at re-login, even when quit in the previous session.

There is a helper LaunchAgent running, but I don't know what it does.

**Comment by timfallmk** [comment]
Any updates on this? Still appears in the current version.

**Comment by mydigitalself** [comment]
There's an entirely new version of the app coming out very soon, we've consolidated the Mac+Linux+Windows codebase using nw.js. So the new Mac version will be very similar to the old one, but rather than embedding Safari it basically uses Chromium. Has some small feature additions, like sound on notifications, but otherwise will be largely the same. 

Will see if we can reproduce this same issue, although we never managed to reproduce on the current version.

The launchAgent is either the updater or the menubar icon, not sure, not entirely my area. @suprememoocow  @trevorah  ?

**Comment by thejameskyle** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen this.
