### ISSUE TITLE
Left menu rooms are difficult to distinguish

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#385]
If you are part of several communities with similar room names ("discuss", "chat", "user", "group" etc), then picking the correct room form the left menu can be difficult.

A quick win would be to use stop cutting room owner names off long room names, and switch to https://gitter.im/explore style shortening.

via @olizilla

**Comment by trevorah** [comment]
From @mydigitalself:

> With the icon changes in the left menu, rooms that get truncated may have difficultly determining which room is which. For example: 
https://gitter.im/gitterHQ/gitter?at=5580b53f3039387b157796fd

Reopening.

**Comment by trevorah** [comment]
Pic for the lazy:

![](https://files.gitter.im/gitterHQ/gitter/jKzr/blob)

**Comment by dozoisch** [comment]
:+1:

**Comment by olizilla** [comment]
My original point was, as I help out on `nodeschool`, `nodebots`, `nodenode`, `nodeynodeington`, `nodoubt`, and `noodles` rooms, I had to use my actual brain to really think about what room I needed to use, rather than just skim it for pictures I like I do when I pretend to read books.

Now there are little pictures, I'm much happier. Lock symbols as proposed, and a nicer star would make me super jazzed :tada:

**Comment by hilton** [comment]
Lock icons on the left would be good. It would also be nice to somehow indicate the channel and whether it's private where you type messages so you're less likely to post in the wrong room. At the moment, it's like having a command line without the host name in the prompt…

**Comment by MadLittleMods** [comment]
> Just to follow-up how this was solved on 2016-8-12
> 
>  - If `roomName = groupName`, then do cunning ellipses thing
>  - Hide `"Lobby"` (`defaultRoomName`) and only show the community name instead
>  -  Still do the truncation we do today
> 
> ![](http://i.imgur.com/2ZtfpcV.gif)
>
> https://github.com/gitterHQ/gitter/issues/1350#issuecomment-243312475
