### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by dandv** [gitterHQ/gitter#394]
Drag'n'drop of images is possible, so should be pasting.

**Comment by jmuheim** [comment]
:+1: 

This would be very important for our company, and we're considering to use gitter extensively when this feature is available.

**Comment by damianh** [comment]
:+1:

**Comment by DavidKarlas** [comment]
:+1:

**Comment by stringparser** [comment]
niiiice +1

**Comment by qiemem** [comment]
While this is working in the web client, it doesn't appear to be working in the OS X desktop client. Should it be? (OS X 10.9.5, Gitter 1.162)

**Comment by tnrich** [comment]
Yup, not working for me on OSX :)

**Comment by dandv** [comment]
@waltfy, @mydigitalself, what library did you guys use for image pasting and how happy are you with it?

I was looking to integrate @layerssss (https://github.com/layerssss/paste.js) in a rich editor.

**Comment by waltfy** [comment]
Hey @dandv sorry, I can't recall what library we used at the time.

**Comment by jmuheim** [comment]
@dandv, I'm in the progress of doing the same with paste.js, and here's my approach:

- Apply paste.js to a textarea, and send the pasted image as base64 string to the server
- On the server side, I use https://github.com/carrierwaveuploader/carrierwave for uploads, and there's modification which accepts base64 strings: https://github.com/lebedev-yury/carrierwave-base64

If you don't use the gems mentioned, you for sure can simply catch the base64 string on the server side and transform it into the expected data.

**Comment by layerssss** [comment]
hi, guys, it's great that my work can do a little help. One really cool thing about XMLHttpRequest is you can attach a blob as a file to upload it onto server using multipart request, then no additional base64-decoding code on server is required. (since most server stacks support parsing multipart requests)

```
$('textarea').on('pasteImage', function(ev, data) {
  var fd, xhr;
  xhr = new XMLHttpRequest();
  xhr.open('POST', url, true);
  fd = new FormData();
  fd.append(data.blob, 'clipboard.png');
  return xhr.send(fd);
});
```

however, the ability to use `FormData` is not available on old IE browsers, but really cool if that's not a problem for you http://caniuse.com/#feat=xhr2

**Comment by lerouxb** [comment]
There are issues with this. Pasting an image doesn't work the same as dragging and dropping an image (in Chrome, at least. Not sure about any specs.) and any bit that does work is coincidental, apparently:
https://code.google.com/p/chromium/issues/detail?id=361145
https://code.google.com/p/chromium/issues/detail?id=361980&thanks=361980&ts=1397121059

I happened to deal with this and file bugs against chromium about it last year.

**Comment by dmehra** [comment]
I see this issue is closed, does that mean there will not be support for copy/paste of image from clipboard into the OSX gitter app? That still does not work (drag'n'drop of images does). My project is considering a switch from slack to gitter, including for private channels, but we are fond of pasting screenshots which would be hard to do unless this is fixed.

**Comment by MadLittleMods** [comment]
@dmehra Open a new issue so we can track this better :)

**Comment by dmehra** [comment]
Done, https://github.com/gitterHQ/gitter/issues/1040
