### ISSUE TITLE
can't install android app on my device. 

### ISSUE THREAD

**Issue by NobbZ** [gitterHQ/gitter#513]
I can't install the app on my device.

Android 4.2, 8 inch tablet.

Samsung Galaxy Note 8.0 (SGN 5110)

Google play tells me my device isn't compatible

**Comment by mydigitalself** [comment]
I'm afraid we only support 4.4 and upwards. 
http://cl.ly/image/163R2a1Q3x0R

Are you able to upgrade?

**Comment by NobbZ** [comment]
No, I'm not able to upgrade.

Is there any reason for 4.4? You loose about 80% of the market.
Am 14.01.2015 19:11 schrieb "Mike Bartlett" <notifications@github.com>:

**Comment by mydigitalself** [comment]
The app is largely based around WebView and pre-4.4 before the
Chromium-based WebView this was a dog. Google broke compatibility with the
4.4 release and for a small team like ours to have to maintain this is an
issue.

I think it's also worth noting that Google themselves aren't even doing
security fixes for versions below 4.4. This whole support and android
version fragmentation is a big issue for developers as a whole, and perhaps
they will pay the price in the future as this is much less of a problem in
iOS  where more than 90% of devices are on the most recent two versions
with 70% on the latest version. I think people should factor this in to
their buying decisions because it's only going to negatively affect the
android software ecosystem.

I know that's not the greatest answer, but that's the nature of the
situation.

Having said that, we know many people who have jail broken their devices to
upgrade and are very happy with the results.

**Comment by NobbZ** [comment]
Having rooted my device is just the cause why I can't update... I'm not
eligible anymore to get ota updates now, for applying the update manually I
need access to a windows computer and administrative permissions on that
computer and it needs an USB port. No computer I have access to fulfills
more than 2 of this preconditions.
Am 14.01.2015 20:31 schrieb "Mike Bartlett" <notifications@github.com>:

**Comment by mydigitalself** [comment]
Would https://www.modern.ie/en-us/virtualization-tools do the trick on a computer that has a USB port?

**Comment by NobbZ** [comment]
If I had Access to a Windows license I could simply install on my personal
computer, but I deny to pay for something, that I only use only once a
year...
Am 15.01.2015 18:05 schrieb "Mike Bartlett" <notifications@github.com>:

**Comment by mydigitalself** [comment]
Those images are free.
