### ISSUE TITLE
Sort mention list by recent activity

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#518]
Rather than the seemingly random order it's in today.

**Comment by quintesse** [comment]
There is a mention list? I haven't seen this anywhere it seems.

**Comment by waynew** [comment]
@quintesse the @-mention list. So if you're talking to the most recent `@a`somebody and they happen to be `@aabc` and you have a list of:

```
@aabaa
@aabacadabra
@aabazanzubar
@aabariffic
@aabanana
@aabapple
@aabc
```

Then you have to type `@aabc` to mention the person. I was chatting in  a room, and the person I wanted to talk to was the last match of somewhere greater than 5 characters, which was a pain because not a single other person in that list was chatting at the time. I could've written their name in 2-3 characters - because it was a highly active room (hundreds? of people) I probably had to write a few hundred extra characters over the course of my chatting.

**Comment by quintesse** [comment]
Ah ok, the auto-complete for mentions, now I understand.
I thought you meant that there was a list somewhere of people that mentioned you (which would be very useful)

**Comment by trevorah** [comment]
This should be live now in gitter next and will be in prod shortly. Go to http://next.gitter.im to try it out!
