### ISSUE TITLE
Add features 

### ISSUE THREAD

**Issue by williamd1k0** [gitterHQ/gitter#569]
* I would like to indicate the addition of an option to start the application with windows.
* I would also like to indicate the support at least to Android 4.0

Thanks :smile:

**Comment by mydigitalself** [comment]
Hi there,

The application should start when Windows starts, it's one of the options that's preselected in the Installer. Does yours not? If not, can you please file an issue here: https://gitter.im/gitterHQ/desktop. Thanks.

Right now we have compatibility issues with Android because of how the WebView support in Android was changed in 4.4. We can't commit right now to supporting older versions I'm afraid.
