### ISSUE TITLE
Embedded gist are being truncated 

### ISSUE THREAD

**Issue by sudodoki** [gitterHQ/gitter#576]
Whenever embedding gist into chat, only part of it is visible.
Culprit would be
```
.chat-item__text .embed {
position: relative;
-webkit-transition: max-height 500ms;
transition: max-height 500ms;
overflow: hidden;
max-height: 640px;
}
```
Namely, `max-height` && `overflow: hidden`
If you do `overflow: scroll` it would partially solve the issue - not sure about this change affecting other types of embedded content.

**Comment by mydigitalself** [comment]
Yeah we specifically gave it a max height and truncated it rather than scrolling, the reason for this was having a scroll area in a scroll area becomes a bit awkward, especially since what often happens if you're swiping with a touchpad is that as the gist comes under the mouse, it then scrolls on next swipe.

It's not an ideal solution and will try and figure out a better solve, perhaps having a way to expand it?

**Comment by suprememoocow** [comment]
This is essentially the same issue that we experience with some tweets: https://github.com/gitterHQ/gitter/issues/573

**Comment by mydigitalself** [comment]
Going to close this one and use #573 as it was reported first.
