### ISSUE TITLE
Show organization icon in left navigation

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#603]
This would be seriously cool! It would be so helpful.

**Comment by troupe-admin** [comment]
Can you elaborate? You mean the org avatar?

**Comment by tjconcept** [comment]
Yep. In stead of the generic organization/team icon.

**Comment by mydigitalself** [comment]
I've tried this before, and actually have a little prototype that's been on the backburner for a while that includes this.

A few reasons not to:
1) With the current design, the contrast of having certain images on the dark blue left menu looks a bit crap at times. That can be solved in other ways though.
2) Probably more concerning is that it adds a lot more visual weight to the left. The simple, more uniform, monochrome icons. There's a fair amount going on in the app as it is and I'm concerned this adds clutter.

You can argue that #604 would negate (2), but that would only be for people who have it collapsed. I think most people would have the left menu shown at all times. I have this opinion because, interestingly, in early early versions of the product, the left menu was **always** collapsed, and it made switching rooms a lot more cumbersome. 

Regardless, I'll keep playing with the concept in the background and see if I can figure something out.

I'm going to close this issue as it would be part of a larger initiative and we're suffering a bit from issue noise in our ever-growing list at the moment.

**Comment by tjconcept** [comment]
Interesting feedback. I understand your concerns.

When I'm in a familiar interface, something I use regularly, I'd rather avoid reading anything that's not part of the content. Everything "meta" should preferably be behind an icon - because my brain just recognizes that way faster than I can read. Room names probably fall in between here.
