### ISSUE TITLE
Create room for issue

### ISSUE THREAD

**Issue by omerzimp** [gitterHQ/gitter#617]
I'd really like to be able to create rooms for issues and have the converstation pasted over that issue.
That way when discussing something specific it will be recorded and it will enable others to review it later.
You can just add a comment with a link to the room if Github might throttle Gitter from posting API requests.

**Comment by MadLittleMods** [comment]
I do not think each message should be individually posted.

I think a bot like the @gitter-badger should [post a link to the room like it does now](https://github.com/mikepenz/Materialize/pull/3) when adding a badge for a new room.

Having a room for each issue segments a community and forces people to be on top of every room in order to fully contribute and see what is going on.

**Comment by MadLittleMods** [comment]
We don't have any short term plans to support this use case.
