### ISSUE TITLE
Spam content removal

### ISSUE THREAD

**Issue by mr-mig** [gitterHQ/gitter#620]
Hello there.

We had faced a spam attack in our chats: http://github.com/dev-ua.
A bunch of porn pics was posted.

There is a couple of problems:

1. We cannot remove/hide those messages.
2. We cannot easily prevent bots from keep posting stuff from freshly created accounts.

There is a couple of suggestions to deal with those problems:

1. Automatically hide all messages sent from banned account.
2. Give moderators the ability to hide/remove messages from banned accounts.
3. Limit the activity for freshly-created github accounts.

**Comment by webknjaz** [comment]
https://gitter.im/dev-ua/dart
yet another spam post

**Comment by IRus** [comment]
+1

**Comment by webknjaz** [comment]
Yet another spamming today.

**Comment by c0bra** [comment]
+1

**Comment by c0bra** [comment]
Being able to report entire accounts for a global ban would be good as well.

**Comment by bb010g** [comment]
:+1:

**Comment by JoyNeop** [comment]
:+1:

**Comment by NikolayS** [comment]
+1

**Comment by NikolayS** [comment]
+1

**Comment by adriaanm** [comment]
+1 the lack of this feature gives me pause in continuing to use gitter for our OSS communication channels

**Comment by BerkeleyTrue** [comment]
+1

**Comment by abhisekp** [comment]
:+1:

**Comment by SaintPeter** [comment]
We had a recent issue on the Free Code Camp Main:
:point_up: [November 17, 2015 1:24 PM](https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=564b9b053bff82362c335c10)

We need a rate limit on users posting.  They can cut and paste a really amazing amount of content.  In our case this was partially compounded by our bot (which we are fixing), but limiting total characters that someone can post might be a good idea.  You could do some data analysis to figure out what an average rate is and what peaks are, to determine what is "reasonable".

**Comment by FroMage** [comment]
+1

**Comment by rvraghav93** [comment]
+1e10

Any reason why this is not yet implemented? I feel this feature is of considerable importance to any modern chat service...

**Comment by BerkeleyTrue** [comment]
I believe it's on its way

**Comment by bb010g** [comment]
@BerkeleyTrue Source?

**Comment by MadLittleMods** [comment]
@bb010g Community moderation is something we are looking to address soon.

**Comment by emoon** [comment]
Has this been implemented yet? I have faced this issue as well.

**Comment by esden** [comment]
At least give the channel admins the ability to delete posts. That is really the bare minimum.

**Comment by rmeertens** [comment]
+1

**Comment by TsubasaK111** [comment]
Much agree, we're hesitating to use Gitter in our services because of this missing feature.

**Comment by goodfeli** [comment]
+1

**Comment by agibsonccc** [comment]
We aren't hit with this as much but deleting messages for admins is a fairly basic feature that would improve things ALOT. I see recruiter posts in our channel and can't delete them only ban.

**Comment by MadLittleMods** [comment]
@agibsonccc If you think the recruiter spammed across many rooms, you can send a message to support@gitter.im and we can take care of it. Include a permalink to the message.

**Comment by Garbee** [comment]
If it is spam, we don't want it sitting around for someone at gitter to get around to reviewing it and doing something. It should just be removed to keep people from responding to it and adding more noise to the room (yes, some people do try to respond.)

Checking for admin access to a channel and letting those people delete any message should be a trivial addition. It is insane that an open chat platform has been around this long and yet doesn't provide this basic functionality to operators.

It is getting to the point where I personally have already left a few channels because of spam problems and am getting close to leaving the Gitter platform entirely because it is simply too difficult to deal with in rooms that get spammed often.

**Comment by NikolayS** [comment]
"send a message to support@gitter.im" is a bad answer to this issue.

**Comment by agibsonccc** [comment]
I have to agree here. Delete/ban for admins should be pretty simple to add
here...its not like we are asking you to build a machine learning based
spam filter :(

On Aug 28, 2016 01:07, "NikolayS" <notifications@github.com> wrote:

"send a message to support@gitter.im" is a bad answer to this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitterHQ/gitter/issues/620#issuecomment-242925656>, or mute
the thread

**Comment by gavofyork** [comment]
Gitter is now being used as a scam tool for our project. The scammer creates a new account, joins our channel and posts a link to their scam site (cunningly made to look similar to our official releases page). Banning them doesn't help as they can create new users at near zero cost.

Please, guys, get this feature in before we are forced to switch to Slack.

**Comment by MadLittleMods** [comment]
Hey @gavofyork,

You can read more about our stance on moderating here, https://github.com/gitterHQ/gitter/issues/332#issuecomment-161271117

You can give us a permalink to the trouble messages in [`gitterHQ/gitter`](https://gitter.im/gitterHQ/gitter) or send a message to support@gitter.im, and we can delete them. If things are becoming out of hand, we can chat more about a more effective strategy. I have also added a new issue about an idea to better indicate messages from banned users may be dangerous, feel free to give it a :+1: to help prioritize https://github.com/gitterHQ/gitter/issues/1468

**Comment by gavofyork** [comment]
From your "stance on moderating":

> This includes ... giving administrators the ability to delete messages and for the community to flag messages. 

Yeah that's what I'm wanting. When is it likely to happen?

If you absolutely insist to place each and every deletion action through some super-moderator under your employ (rather than trust the very people who created the software behind the community), then at least automate the process rather than give us this 1995-era process of going into a separate chatroom, trying to get a moderator's attention and reporting it under plaintext. A simple "flag for deletion" button would solve the problem 80% and still keep you feeling like you were in ultimate control of moderation. Or even let admins moderate directly but provide a streamlined appeals process for users who feel they're being mistreated.

All we are trying to do is to ensure dangerous links are not posted and that people don't get scammed. Your ideals might be in the right place, but the practicality you are are forcing on us means that you are facilitating the bad guys here. Doing the wrong thing for the right reasons is still doing the wrong thing.

**Comment by Garbee** [comment]
So, the recommended solution is simply to style banned user messages differently rather than allow outright deletion.

Let's say someone comes into a room and spams some religious stuff which is completely off-topic and not useful to anyone ever in the chatroom. We delete the user, however, their messages stay in-tact for people to see in the future when it isn't worth their time even looking at as it is off-topic completely to the channel in question.  This is extremely weird to just style differently. Instead of styling, we should be able to *remove* nonsense posted into channels by spammers/scammers.

What I am getting the feeling of from gitter is that you don't care about communities being able to truly moderate themselves because you don't trust a few people who have requested deletions. Well, I for one have seen numerous things that are a no-brainer to just delete yet I have no idea how to do it. Apparently, we need to get in touch with a human somehow, but that is made clear in no way. Not to mention, just pure wasteful of administrators' time when we could just delete it right off in our channel and be on our way.

If you don't trust repository admins to moderate their repositories discussion, then why should the admins trust you to run the chat platform for them?

**Comment by MadLittleMods** [comment]
Any room admin can now delete messages from other users now.

If you are getting attacked by spam, please still report these users in the [`gitterHQ/gitter`](https://gitter.im/gitterHQ/gitter) room or support@gitter.im so we can take care of them on a global level.

---

You can also manage room admins via the Permissions modal, Room settings -> Permissions

![](http://i.imgur.com/YcyL4Pq.png)

**Comment by agibsonccc** [comment]
Thanks. Seriously.

**Comment by esden** [comment]
Finally! Thank you! :)
