### ISSUE TITLE
Javascript alerts executed on embedded CodePen

### ISSUE THREAD

**Issue by storbeck** [gitterHQ/gitter#648]
When embedding a codepen with a javascript alert, it's executed in gitter. It will execute everytime you switch back to the channel that has it.

I'm not sure if this was originally intended but it can cause a lot of usability issues.

**Comment by agauniyal** [comment]
a cross-site scripting vulnerability

**Comment by mydigitalself** [comment]
We've brought it up with them before when somebody embedded a pen with gratituous sound in it.  There's really not a lot we can do about it short of parsing the emebedded pen and deciding what's ok and what's not.

Any thoughts would be appreciated, but it's somewhat out of our hands.

**Comment by agauniyal** [comment]
Maybe not embedding them inside gitter would solve this , let user open it in another tab. Or anyone could search about HPPT:\\crash-my-browserdotcom , and could post it. Never tried it on gitter , but there was teapot once featured on PH ;)

**Comment by lucaswerkmeister** [comment]
If you still want thoughts, my opinion is that it’s a horrible idea to embed *and run* any codepens posted in the chat, and you simply shouldn’t do that at all. If it’s possible to embed codepens without automatically running them (provide an explicit “run” button), do that, otherwise IMO a stupid link instead of an embed is totally fine.
