### ISSUE TITLE
Accidental rooms being created (no confirmation) - slow filter

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#698]
I see this all the time in @gitter-badger's pull request comments:
> This was done by accident, the gitter interface jumps all over the place & I clicked wrong

When you select a repo in the modal, the room is created immediately.
![screen shot 2015-05-21 at 11 14 38](https://cloud.githubusercontent.com/assets/298742/7746494/ab5943ae-ffaa-11e4-9bbb-51dae19a9110.png)

Because the modal has more than one input, most actually expect it to behave like a form (i.e have a submit button).

**Comment by MadLittleMods** [comment]
:+1:

**Comment by yamalight** [comment]
so much anxiety with this one, please address :+1:

**Comment by nkuehn** [comment]
+1  sucks. i just accidentally created pull requests in production repos of our organization.

**Comment by nchammas** [comment]
I didn't even see the checkbox when I went through this flow.

This is what I saw:

![screen shot 2015-10-25 at 2 48 48 pm](https://cloud.githubusercontent.com/assets/1039369/10717241/bffe0242-7b27-11e5-8abc-07bbc8846503.png)

So I was surprised when, after I ignored a later button asking if I wanted a PR, I got the PR anyway.

This window needs to be fixed somehow to always show that checkbox clearly, and it would be better if the checkbox defaulted to unchecked until this flow is fixed.

(Posting here since #19 was closed in favor of this issue.)

**Comment by legnaleurc** [comment]
Accidentally created a pull request +1, really sucks ass.

**Comment by mydigitalself** [comment]
Alleviated this a bit by making the list of repositories a fixed height to prevent the jumping of the search area. Should be shipped into production next week.

**Comment by miohtama** [comment]
When you are maintaining  ahigh number of repositories (>1000) this becomes more accidental due to a UI slowdowns.

**Comment by mydigitalself** [comment]
It used to be a really big problem as the filter input moved during load, so as you clicked on the filter, you then clicked on a repo. Can't see how this is still much of a problem now @miohtama ?

**Comment by MadLittleMods** [comment]
@mydigitalself From a ticket, I think @miohtama meant that with a large number of repos; initially wasn't clear that the list was just taking a while to load them in (better loading state), and that the filtering takes a while to apply which could cause a switch just as you click.

**Comment by MadLittleMods** [comment]
The new create room modal doesn't use a click to create process anymore. You select the repo from the typeahead, then click create.

![](http://i.imgur.com/myq9Bf4.png)

![](http://i.imgur.com/3MgEOTK.png)
