### ISSUE TITLE
Can't upload SVG files

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#721]
SVG files are currently returning errors.

If you download this: http://www.clipartsfree.net/svg/summer-hot-dog_Clipart_svg_File.svg and then drag and drop you will get an error about metadata.

**Comment by trevorah** [comment]
Fixed by disabling image manipulation stuff on svgs so that we treat them as basic files. We still get the image preview though:
![screen shot 2015-11-11 at 16 53 14](https://cloud.githubusercontent.com/assets/298742/11096990/c0233fba-8894-11e5-8f66-7df1e8fd45de.png)
(first is jpg of border collie, second is svg of border collie)
