### ISSUE TITLE
Add ability to create a GitHub issue from Gitter message

### ISSUE THREAD

**Issue by StephenOTT** [gitterHQ/gitter#745]
Gitter is becoming more commonly used to solve issues to problems rather than creating a issue in the github issue queue.  This is a problem when search and reference become a problem.  Would be great if there was a markdown command that could be added to the gitter message that would create a issue from the message

**Comment by dasher** [comment]
@Gaelan 17:09
@dasher Yes, but IMO it would be nicer to have comments correctly connected to users, instead of having a comment by person A saying “person B said blah."

@dasher 17:33
@Gaelan It's a mixed bag to be honest - proxy'ing each person in the conversation to the github issue without their consent - a mention is ok but posting their behalf. While I agree - ideally it shouldn't be a problem

@StephenOTT 17:37
Ya. as mentioned it likely a User Pref issue not a technical issue

**Comment by StephenOTT** [comment]
merging all of the messages into a single comment means that you loose the benefits of individual comments: such as permalink to comments

**Comment by dasher** [comment]
well merging has other issues - such as: ;)

@StephenOTT 18:02
I love the smell of orange bananas on a Sunday morning

**Comment by MadLittleMods** [comment]
Directly related to https://github.com/gitterHQ/gitter/issues/247, where `/issue` was suggested to interact with issues.

Also related to https://github.com/gitterHQ/gitter/issues/611

**Comment by MadLittleMods** [comment]
Move discussion to https://github.com/gitterHQ/gitter/issues/611
