### ISSUE TITLE
Web client seems to randomly reorder and delete messages

### ISSUE THREAD

**Issue by pchiusano** [gitterHQ/gitter#770]
I don't have any steps to reproduce, but we've noticed messages getting reordered (even hours after being sent in some cases) and deleted here in this room: https://gitter.im/unisonweb/platform

It's been happening with some regularity. As an example, [this group of messages](https://gitter.im/unisonweb/platform?at=55a66ab57632bfcf1055c149) was placed before [this group](https://gitter.im/unisonweb/platform?at=55a66ab57632bfcf1055c149) of messages even though they were sent in a different order. (The second group was actually sent the _night before_).

After refreshing the room just now it looks like everything is currently ok and in the correct order. But I think we've noticed that refreshing does not always fix it... it almost seems like the server is in a funky state.

This issue is pretty annoying, especially if you're in the middle of a conversation and a message you send gets randomly grouped with some message from way earlier.

**Comment by trevorah** [comment]
@pchiusano this was originally caused by some app servers taking longer to process new messages. This meant that when you send messages in quick succession, some would be parsed quicker than others, and the timestamps would get messed up.

We've put in a fix to stop the processing speed from affecting the message ordering, and this weekend we will be doing some maintenance to fix the processing speed itself.

**Comment by pchiusano** [comment]
Glad to hear it, thanks for the reply.
