### ISSUE TITLE
Mac OSX client STILL cluttering logfiles

### ISSUE THREAD

**Issue by michaelaye** [gitterHQ/gitter#773]
I had reported this in August last year or so via Twitter, and after the long awaited update for the OSX client, this has still not been resolved today:

<img width="453" alt="screenshot 2015-07-16 11 03 11" src="https://cloud.githubusercontent.com/assets/69774/8729753/45cd748e-2baa-11e5-9302-8b26f82b45d7.png">

**Comment by mydigitalself** [comment]
Hi Michael, sorry this hasn't been addressed yet. We've been really focused on infrastructure and have the Mac release 95% complete and hasn't had any focus, in particular because the existing one works pretty well.

One small suggestion, why don't you just click on the item in Console.App and then click on the Ignore Sender button at the top, then you won't see these ever again?

**Comment by michaelaye** [comment]
Thanks for your suggestion, that helps a bit. But do I assume correctly that that is only a filter and not preventing the write into logfiles?

**Comment by MadLittleMods** [comment]
@michaelaye Is this still a problem, I am not seeing these messages in the console?

**Comment by michaelaye** [comment]
Yep.
<img width="1197" alt="screenshot 2016-02-04 14 45 01" src="https://cloud.githubusercontent.com/assets/69774/12830708/e8fcc20c-cb4d-11e5-94cc-b78d27b0576f.png">

**Comment by MadLittleMods** [comment]
@michaelaye Thanks, I didn't know about the "Console" app on Mac that was showing these messages.

Some brief testing shows that once we release the nw.js version of the desktop app for mac(current mac app is using a Safari backend), this shouldn't be a problem anymore. You can [make your own build now](https://github.com/gitterHQ/desktop) or stay tuned.
