### ISSUE TITLE
Date is nearly invisible on MacBook Retina

### ISSUE THREAD

**Issue by Fsteinca** [gitterHQ/gitter#810]
Check the picture, please note how the date is quite clear, only if you know where to look and move the cursor over it. Note also, these faint lines showed up with the last MacOS 10.10.4 update.
(MacBook Pro (Retina, 13-inch 10.10.4)
![img_0936](https://cloud.githubusercontent.com/assets/12449660/9122401/9f4f9728-3c3d-11e5-9bdc-26e08e30c9b3.JPG)

**Comment by mydigitalself** [comment]
This is fairly intentional as the timestamp of the message should have less affordance than the message itself.

Having said that, we've improved the contrast of this a little, and even more so when you hover the chat message, and that's available on Gitter Next (https://gitter.zendesk.com/hc/en-us/articles/203904511-Gitter-Next)

**Comment by Fsteinca** [comment]
Nice. I'm now on Gitter Next. Thanks

**Comment by MadLittleMods** [comment]
Related to #771
