### ISSUE TITLE
Mobile code

### ISSUE THREAD

**Issue by georgiel** [gitterHQ/gitter#850]
And no way to shift enter on mobile, which stops multi-line code segments

**Comment by MadLittleMods** [comment]
@georgiel *do not try:* If you start typing the triple backticks first, then you you enter multiline code no problem.

Entering in triple backticks makes you go in to [compose mode automagically](https://gitter.zendesk.com/hc/en-us/articles/201302311-Compose-mode) and you run into gitterHQ/gitter#793 where you can't send the message because you are in compose mode(requires `ctrl + enter`) and there is no toggle visible in the portrait mobile/Android app.

**Comment by MadLittleMods** [comment]
Closing in favor of #793 which will fix this.
