### ISSUE TITLE
Alert notification sound every few seconds

### ISSUE THREAD

**Issue by deltreey** [gitterHQ/gitter#852]
Not every time, but about 50% of the time when I have the gitter app running on Windows 10 I get notification sounds every few seconds.  There is no visual indication of notification (and I'm not being notified of anything as recieving messages is not a requirement).  It's difficult to reproduce (It is happening at the moment) in a consistent way.  I have to turn off notification sounds ( Gitter > Notification Sounds > None ) to make it stop.  I can't get it to happen by closing and re-opening the app.  Instead, it seems to require a restart (gitter is configured to run at startup).

**Comment by georgiel** [comment]
:+1:

**Comment by trevorah** [comment]
That would be the autoupdate notification logic bug (https://github.com/gitterHQ/desktop/issues/73). It is fixed in the latest version of the app, which (ironically) your version is trying to alert you about. If you dont want to go through the autoupdate process, you can just download and install the latest version from https://gitter.im/apps and your settings will be preserved.

**Comment by deltreey** [comment]
didn't find a way to set up auto-update.  Went ahead and updated manually per your link.  Seems to be OK now.  I'll keep an eye on it and re-open the issue if it's a problem.

**Comment by trevorah** [comment]
Cool, thanks.
