### ISSUE TITLE
:thumbsup: should come up before :thumbsdown: in autocomplete

### ISSUE THREAD

**Issue by basicallydan** [gitterHQ/gitter#988]
I'm not sure how this is determined but I suspect it's simple alphabetical, so it may be a lot of unnecessary work. However, I was recently having a chat about a feature with my open-source compadre @M-Zuber on our gitter channel and this happened:

<img width="650" alt="screenshot 2015-11-22 15 56 19" src="https://cloud.githubusercontent.com/assets/516325/11322860/cd0e71ae-9131-11e5-828e-3268753e26d2.png">

I know I'm being picky and a little bit careless but I wonder how many people have this problem, expecting thumbs-up to come up first but getting thumbs-down, and hitting enter before they realise their mistake.

Happy to figure out how to do it myself if it's not gonna cause a load of huge changes, but just wanna see if this is worth doing.

EDIT: FYI, GitHub itself has `:thumbsup:` first.

**Comment by M-Zuber** [comment]
:+1: 
It has a happened a lot to me also.

as a side note `GitHub` seems to have a workaround by not using the text name
![image](https://cloud.githubusercontent.com/assets/4746537/11322894/ec75250c-9108-11e5-98bb-c5bb27f96cf7.png)

![image](https://cloud.githubusercontent.com/assets/4746537/11322901/fe4ee7f4-9108-11e5-9c83-e6c7844b93a3.png)

**Comment by abhisekp** [comment]
:+1:

**Comment by posita** [comment]
> I'm not sure how this is determined but I suspect it's simple alphabetical, so it may be a lot of unnecessary work.

GitHub maintains several useful, but non-standard aliases (e.g., try typing `:scared` and `:fearful:` will show up). Emojis maintain aliases as well (`:+1:` and `:thumbsup:` have the same icon, as do `:-1:` and `:thumbsdown:`; see <http://www.emoji-cheat-sheet.com/>). In GH, the list is sorted alphabetically by *resolved* Emoji code. More specifically, `:thu` resolves to the aliases `:thumbsdown`, `:thumbsup`, and `:thunder`, which resolve to `:-1:`, `:+1:`, and `:zap:`, respectively. When the latter list is sorted alphabetically, `:+1:` appears before `:-1:`. I'm assuming this is because the byte code for `+` (`0x43`) comes before (i.e., is less than) the byte code for `-` (`0x45`).

Gitter may want to emulate GH's Emoji resolution. But if not, complainants can try to get in the habit of typing `:+1:` or `:-1:` instead of `:thumbsup:` or `:thumbsdown:`.

However, I'm not sure it makes sense to pervert the sort order for just `:thumbsup:` and `:thumbsdown:` without instituting an alias system similar to GitHub's. FWIW, HipChat lists its emoticon codes alphabetically, which puts `(thumbsdown)` before `(thumbsup)` (HipChat uses a parenthetical notation).

Also, Gitter allows you to got back and edit your comments, so you can make changes if you screw up. It also supports `s/.../.../` notation, so in your next message, you can type `s/:thumbsdown:/:thumbsup:/` (or just `s/down:/up:/` so long as that's specific enough for your previous message) and it should be corrected.

**Comment by posita** [comment]
These are more extensive than GH's list, but here are some examples of others' attempts at Emoji aliases:

* https://github.com/muan/emoji/blob/47ac2c12cfe73d313ce68e4277d8cd07bfca58ea/emojis.json
* https://gist.github.com/ta2gch/6af77cef5b48fd17b989
*https://github.com/carpedm20/emoji/blob/638a362cd186b101e5d7098c7e965533705cf7f2/emoji/unicode_codes.py

**Comment by MadLittleMods** [comment]
Use `:+1:` and `:-1:`

It isn't worth complicating the code to sort these few emojis.
